config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  root "marketplace#index"
 
  devise_for :users, :controllers => {:registrations => "users/registrations",
                                      :omniauth_callbacks => "users/omniauth_callbacks"}
  resources :cart_invoice, only: [:new, :create]
  resource :charges, only: [:new, :create]
  resources :marketplace, only: [:index, :show]
  resources :dashboard, only: [:index]
  resources :cart_items ,only: [:create, :index, :destroy]
  resources :products
  resources :invoices, only: [:new, :create, :index, :show]
  resources :permissions, only: [:index, :update] do
    collection do
      put :update_role
      get :buyers
      get :sellers
    end
  end
  resources :buyers, only: [:index] do
    member do
      get :invoices
    end
  end
  resources :sellers, only: [:index]
  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  after_create_commit { UpdateAddedToCartProductsJob.perform_later self}

  scope :get_seller_items, lambda { |user_id| joins(:product).where( products: {user_id: user_id}) }
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  attr_accessor :quantity, :product_id
  belongs_to :user
  has_many :invoice_details, dependent: :destroy
  has_many :products, through: :invoice_details

  after_save :send_sms

  def initialize_invoice_from_cart(user)
    self.status = 'Order Placed'
    self.payment_method = 'Cash On Delivery'
    cart_items = user.cart.cart_items.all
    cart_items.each do |item|
      self.invoice_details.new(product_id: item.product_id, quantity: item.quantity.to_i, price: item.product.price)
      update_product(item)
    end
  end

  private 

  def send_sms
    InvoiceOrderSmsWorker.perform_in(30.seconds, self.user_id, self.id)
  end

  def update_status
    self.status = "Order Placed"   
  end

  def update_product(item)
    (item.product.stock - item.quantity > 0) ? item.product.decrement!(:stock, item.quantity) : item.product.update_attribute(:stock, 0)
  end

end

app/models/invoice_detail.rb
class InvoiceDetail < ApplicationRecord
  belongs_to :invoice
  belongs_to :product

  after_create_commit { UpdateSoldProductsJob.perform_later self}

  scope :get_seller_items, lambda { |user_id| joins(:product).where(products: {user_id: user_id} ) }
  
  def subtotal
    self.quantity * self.price
  end

end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, AvatarUploader
  belongs_to :imageable, polymorphic: true, optional: true

end

app/models/product.rb
class Product < ApplicationRecord
  
  belongs_to :user
  has_many :cart_items
  has_many :carts, through: :cart_items
  has_many :invoice_details
  has_many :invoices, through: :invoice_details
  has_one :picture, as: :imageable, dependent: :destroy

  accepts_nested_attributes_for :picture

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      unscoped
    end
  end

end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
require 'twilio.rb'
class User < ApplicationRecord
  include Twilio

  has_many :products
  has_one :picture, as: :imageable, dependent: :destroy
  has_one :cart, dependent: :destroy
  has_many :invoices, dependent: :destroy
  rolify
  
  scope :has_cart_item, lambda { |id| joins(:cart).where( carts: {id: id}).first}

  after_create :assign_default_role, :create_cart
  after_update :send_sms_to_admin

  accepts_nested_attributes_for :picture
  #Validations
  validates :first_name, presence: true, length: {maximum:20}
  validates :last_name, presence: true, length: {maximum:20}
  validates :phone, uniqueness: true, allow_blank: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  def assign_default_role
    self.add_role(:buyer) if self.roles.blank?
  end
    
  def is_admin?
    has_role? :admin
  end

  def is_seller?
    has_role? :seller
  end

  def is_buyer?
    has_role? :buyer
  end

  def change_role(operation) 
    operation == "true" ? (self.add_role :seller) : (self.remove_role :seller) 
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.name.split.first
      user.last_name = auth.info.name.split.last
      user.profile_pic = auth.info.image
    end
  end
  private

  def send_sms_to_admin
    delete_existing_worker
    SendSmsWorker.perform_in(10.seconds, self.id) 
  end


  def create_cart
    if self.cart.blank?
      cart = self.build_cart     
      cart.save
    end
  end

  def delete_existing_worker
    jobs = Sidekiq::ScheduledSet.new
    jobs.each do |job|
      job.delete if job.klass == 'SendSMSWorker' && job.args.include?(id)
    end
  end

end

app/controllers/base_controller.rb
class BaseController < ApplicationController

  before_action :authenticate_user!
  
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController

  before_action :require_admin
  def index
    @buyers = User.select{ |user| user.is_buyer? }
  end

  def invoices
    @invoices = Invoice.where(user_id: params[:id]).all
  end
  
  private

  def require_admin
    unless current_user && (current_user.has_role? :admin)
      flash[:notice] = "You are not an admin"
      redirect_to root_path
    end        
  end

end

app/controllers/invoices_controller.rb
class InvoicesController < BaseController
  
  def index
    @invoices = current_user.invoices
  end

  def new
    @cart_items = current_user.cart.cart_items
  end

  def create
    @invoice = current_user.invoices.new(invoice_params)
    @invoice.initialize_invoice_from_cart(current_user)
    if @invoice.save
      current_user.cart.cart_items.destroy_all
      flash[:notice] = "Order successfully added. Please proceed with payment to place your order."
      redirect_to invoice_path(@invoice)
    else
      flash[:notice] = "Order could not be placed."
      redirect_to marketplace_index_path
    end    
  end


  def show
    @invoice = current_user.invoices.where(id: params[:id]).first
    if @invoice.nil?
      flash[:notice] = "Invoice could not be found."
      redirect_to invoices_path
    end
  end

  private
  
  def invoice_params
    params.require(:invoice).permit(:shipping_address, :total)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper

  def calculate_total(total, product_id, quantity)
    total = total + current_user.cart.products.where(id: product_id).first.price * quantity
  end
   
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/marketplace_helper.rb
module MarketplaceHelper
end

app/helpers/permission_helper.rb
module PermissionHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/invoices/_invoices_list.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <% if invoices.blank? %>
      <p>You have no orders yet.</p>
    <% else %>
      <table class="table">
        <th>Order Date</th>
        <th>Shipping Address</th>
        <th>Total</th>
        <th>Delivery Date</th>
        <th>Status</th>
        <th>Payment Method</th>
        <th>Options</th>
        <% invoices.each do |invoice| %>
          <tr>
            <td><%= invoice.created_at %></td>
            <td><%= invoice.shipping_address %></td>
            <td><%= invoice.total %></td> 
            <td><%= invoice.status == "Delivered" ? invoice.delivery_date : "Not yet Delivered" %></td>
            <td><%= invoice.status %></td>
            <td><%= invoice.payment_method %></td>
            <td><%= link_to 'View Details', invoice_path(invoice) %></td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
</div>

app/views/invoices/index.html.erb
<%= render partial: 'invoices_list', locals: { invoices: @invoices } %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= link_to 'Back to All Products', marketplace_index_path %></h3>
  </div>
</div>

app/views/invoices/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h3> Invoice </h3>
    <table class="table">
      <th>Name</th>
      <th>Image</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Total</th>
      <% total = 0 %>
      <% @cart_items.each do |item| %>
        <tr>
          <% product = current_user.cart.products.where(id: item.product_id).first %>
          <td><%= product.name %></td>
          <td>
            <% if product.picture %>
              <%= image_tag(product.picture.image_url(version: product.picture.image.file.version), width: 50, height: 50) %>
            <% end %>
          </td>
          <td><%= product.price %></td>
          <td><%= item.quantity %></td> 
          <td><%= product.price * item.quantity %></td>
          <% total = calculate_total(total, item.product_id, item.quantity) %>
        </tr>
      <% end %>
    </table>
    <p> Total : <%= total %> </p>
    <%= form_for :invoice, url: invoices_path do |f| %>
      <div class="form-group">
        <%= f.label :shipping_address %><br>
        <%= f.text_field :shipping_address, class: "form-control" %>
      </div>
        <%= hidden_field_tag 'invoice[total]', total %>
      <p>
        <%= f.submit 'Order Products', class: "btn" %>
      </p> 
    <% end %>
  </div>
</div>

app/views/invoices/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <p class="lead"> <b>Invoice Details</b> </p>
    <p class="lead"><b>Status:</b> <%= @invoice.status %></p>
    <p class="lead"><b>Shipping Address:</b> <%= @invoice.shipping_address %></p>
    <p class="lead"><b>Total:</b> <%= @invoice.total %></p>
    <p class="lead"><b>Payment Method:</b> <%= @invoice.payment_method %></p>

    <table class="table">
      <th>Product</th>
      <th>Image</th>
      <th>Price</th>
      <th>Quantity</th>
      <% @invoice.invoice_details.each do |item| %>
        <tr>
          <% product = @invoice.products.where(id: item.product_id).first %>
          <td><%= product.name %></td>
          <td><%= image_tag(product.picture.image_url(:thumbnail, version: product.picture.image.file.version), :width => 50, :height   => 50) %></td>
          <td><%= item.price %></td> 
          <td><%= item.quantity %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>
<% if @invoice.status = "Payment Pending" %>
  <div class="row">
    <div class="col-md-2 col-md-offset-5">
      <%= form_tag charges_path do %>
        <script
          src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="pk_test_MDhohq2CR0zbcIFwwW6qK1FD"
          data-amount= "<%= @invoice.total %>"
          data-name="Stripe.com"
          data-description="Widget"
          data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
          data-locale="auto"
          data-zip-code="true">
        </script>
        <%= hidden_field_tag 'total', @invoice.total %>
        <%= hidden_field_tag 'invoice_id', @invoice.id %>
      <% end %>
    </div>
  </div>
<% end %>
</br>
</br/>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= link_to 'See All Orders', invoices_path %>
  </div>
</div>