config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  root "marketplace#index"
 
  devise_for :users, :controllers => {:registrations => "users/registrations",
                                      :omniauth_callbacks => "users/omniauth_callbacks"}
  resources :cart_invoice, only: [:new, :create]
  resource :charges, only: [:new, :create]
  resources :marketplace, only: [:index, :show]
  resources :dashboard, only: [:index]
  resources :cart_items ,only: [:create, :index, :destroy]
  resources :products
  resources :invoices, only: [:new, :create, :index, :show]
  resources :permissions, only: [:index, :update] do
    collection do
      put :update_role
      get :buyers
      get :sellers
    end
  end
  resources :buyers, only: [:index] do
    member do
      get :invoices
    end
  end
  resources :sellers, only: [:index]
  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  
  belongs_to :user
  has_many :cart_items
  has_many :carts, through: :cart_items
  has_many :invoice_details
  has_many :invoices, through: :invoice_details
  has_one :picture, as: :imageable, dependent: :destroy

  accepts_nested_attributes_for :picture

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      unscoped
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < BaseController
  
  before_action :require_admin_or_seller

  def index
    @products = current_user.products
  end

  def new
    @product = current_user.products.new
    @product.build_picture
  end

  def create
    product = current_user.products.new(product_params)    
    if product.save
      flash[:notice] = "Product successfully added."
      redirect_to products_path
    else
      flash[:notice] = "Product could not be created."
      redirect_to products_path
    end
  end

  def show
    @product = current_user.products.where(id: params[:id]).first
    if @product.blank?
      flash[:notice] = "Product not found."
      redirect_to products_path
    end  
  end  

  def destroy
    product = current_user.products.where(id: params[:id]).first
    if product.destroy
      flash[:notice] = "Product deleted successfully."
      redirect_to products_path
    else
      flash[:notice] = "Product could not be deleted."
      redirect_to products_path
    end
  end


  def edit
    @product = current_user.products.where(id: params[:id]).first
  end

  def update
    @product = current_user.products.where(id: params[:id]).first
    if @product.update(product_params)
      flash[:notice] = "Product successfully updated."
      redirect_to products_path
    else
      flash[:error] = @product.errors.full_messages.join(',')
      render 'edit'
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :brand, :category, :price, :stock, :description, picture_attributes: [:image])
  end

  def require_admin_or_seller
    unless current_user && ((current_user.has_role? :admin) || (current_user.has_role? :seller))
      flash[:notice] = "You dont't have the privileges to view this page"
      redirect_to root_path
    end     
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </p>

  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>

  <p>
    <%= f.label :category %><br>
    <%= f.select :category, ['Electronics', 'Clothing', 'Home and Furniture', 'Books and Stationery', 'Accessories']%>
  </p>

  <p>
    <%= f.label :stock %><br>
    <%= f.number_field :stock, min: 1 %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
  <%= f.fields_for :picture do |p| %><br>
    <%= p.hidden_field :image_cache %>
    <%= p.file_field :image %>
  <% end %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
  
<% end %>

app/views/products/edit.html.erb
<h3>Update Product</h3>
<%= render 'form' %>

app/views/products/index.html.erb
<h1>Products</h1>
<h3><%= link_to 'Add New Product', new_product_path %></h3>
<% if @products.first.nil?  %>
  <p> Sorry, you have not added any products yet. </p>
<% end %> 
<table class="table">
  <tr>
    <th>Name</th>
    <th>Brand</th>
    <th>Category</th>
    <th>Price</th>
    <th>Stock</th>
    <th>Image</th>
    <th colspan=3 >Options</th>
  </tr>
  <% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.brand %></td>
    <td><%= product.category %></td>
    <td><%= product.price %></td>
    <td><%= product.stock %></td>
    <td>
      <% if product.picture %>
        <%= image_tag(product.picture.image_url(:thumbnail, version: product.picture.image.file.version), width: 50, height: 50) %>
      <% end %>
    </td>
    <td><%= button_to 'Remove', product_path(product), method: :delete %></td>
    <td><%= button_to 'Show', product_path(product), method: :get %></td>
    <td><%= button_to 'Edit', edit_product_path(product), method: :get %></td>
  </tr>
  <% end %>
</table>

app/views/products/new.html.erb
<h3>New Product</h3>
<%= render 'form' %>

app/views/products/show.html.erb
<div class="container">
  <div class="col-md-3">
  <%= image_tag(@product.picture.image_url(version: @product.picture.image.file.version), width: 200, height: 200) %>
  </div>
  <div class="col-md-4">
  <ul>
    <p> <%= @product.name %></p><br/>
    <p> <%= @product.brand %></p><br/>
    <p> <%= @product.category %></p><br/>
    <p> <%= @product.price %></p><br/>
    <p> <%= @product.description %></p><br/>
    <% if @product.stock > 0 %>
      <p> Available </p>
    <% else %>
      <p> Sold Out </p>
    <% end %>
  </ul>
  </div>
</div>