config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  root "marketplace#index"
 
  devise_for :users, :controllers => {:registrations => "users/registrations",
                                      :omniauth_callbacks => "users/omniauth_callbacks"}
  resources :cart_invoice, only: [:new, :create]
  resource :charges, only: [:new, :create]
  resources :marketplace, only: [:index, :show]
  resources :dashboard, only: [:index]
  resources :cart_items ,only: [:create, :index, :destroy]
  resources :products
  resources :invoices, only: [:new, :create, :index, :show]
  resources :permissions, only: [:index, :update] do
    collection do
      put :update_role
      get :buyers
      get :sellers
    end
  end
  resources :buyers, only: [:index] do
    member do
      get :invoices
    end
  end
  resources :sellers, only: [:index]
  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  after_create_commit { UpdateAddedToCartProductsJob.perform_later self}

  scope :get_seller_items, lambda { |user_id| joins(:product).where( products: {user_id: user_id}) }
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  attr_accessor :quantity, :product_id
  belongs_to :user
  has_many :invoice_details, dependent: :destroy
  has_many :products, through: :invoice_details

  after_save :send_sms

  def initialize_invoice_from_cart(user)
    self.status = 'Order Placed'
    self.payment_method = 'Cash On Delivery'
    cart_items = user.cart.cart_items.all
    cart_items.each do |item|
      self.invoice_details.new(product_id: item.product_id, quantity: item.quantity.to_i, price: item.product.price)
      update_product(item)
    end
  end

  private 

  def send_sms
    InvoiceOrderSmsWorker.perform_in(30.seconds, self.user_id, self.id)
  end

  def update_status
    self.status = "Order Placed"   
  end

  def update_product(item)
    (item.product.stock - item.quantity > 0) ? item.product.decrement!(:stock, item.quantity) : item.product.update_attribute(:stock, 0)
  end

end

app/models/invoice_detail.rb
class InvoiceDetail < ApplicationRecord
  belongs_to :invoice
  belongs_to :product

  after_create_commit { UpdateSoldProductsJob.perform_later self}

  scope :get_seller_items, lambda { |user_id| joins(:product).where(products: {user_id: user_id} ) }
  
  def subtotal
    self.quantity * self.price
  end

end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, AvatarUploader
  belongs_to :imageable, polymorphic: true, optional: true

end

app/models/product.rb
class Product < ApplicationRecord
  
  belongs_to :user
  has_many :cart_items
  has_many :carts, through: :cart_items
  has_many :invoice_details
  has_many :invoices, through: :invoice_details
  has_one :picture, as: :imageable, dependent: :destroy

  accepts_nested_attributes_for :picture

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      unscoped
    end
  end

end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
require 'twilio.rb'
class User < ApplicationRecord
  include Twilio

  has_many :products
  has_one :picture, as: :imageable, dependent: :destroy
  has_one :cart, dependent: :destroy
  has_many :invoices, dependent: :destroy
  rolify
  
  scope :has_cart_item, lambda { |id| joins(:cart).where( carts: {id: id}).first}

  after_create :assign_default_role, :create_cart
  after_update :send_sms_to_admin

  accepts_nested_attributes_for :picture
  #Validations
  validates :first_name, presence: true, length: {maximum:20}
  validates :last_name, presence: true, length: {maximum:20}
  validates :phone, uniqueness: true, allow_blank: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  def assign_default_role
    self.add_role(:buyer) if self.roles.blank?
  end
    
  def is_admin?
    has_role? :admin
  end

  def is_seller?
    has_role? :seller
  end

  def is_buyer?
    has_role? :buyer
  end

  def change_role(operation) 
    operation == "true" ? (self.add_role :seller) : (self.remove_role :seller) 
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.name.split.first
      user.last_name = auth.info.name.split.last
      user.profile_pic = auth.info.image
    end
  end
  private

  def send_sms_to_admin
    delete_existing_worker
    SendSmsWorker.perform_in(10.seconds, self.id) 
  end


  def create_cart
    if self.cart.blank?
      cart = self.build_cart     
      cart.save
    end
  end

  def delete_existing_worker
    jobs = Sidekiq::ScheduledSet.new
    jobs.each do |job|
      job.delete if job.klass == 'SendSMSWorker' && job.args.include?(id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper

  def calculate_total(total, product_id, quantity)
    total = total + current_user.cart.products.where(id: product_id).first.price * quantity
  end
   
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/marketplace_helper.rb
module MarketplaceHelper
end

app/helpers/permission_helper.rb
module PermissionHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/layouts/_sidenav.html.erb
<ul class="nav nav-pills nav-stacked">
  <li class="active"><a href="/dashboard">Dashboard</a></li>
  <% if current_user.is_seller? %>
    <li><%= link_to 'My Products', products_path, class: "active" %></li>
  <% else %>
    <li><%= link_to 'View Users', permissions_path , class: "active" %></li>
    <li><%= link_to 'View Buyers', buyers_path , class: "active" %></li>
    <li><%= link_to 'View Sellers', sellers_path , class: "active" %></li>
  <% end %>
</ul>

app/views/layouts/_topnav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'ShopCon', marketplace_index_path, class:"navbar-brand" %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <% if current_user.is_seller? %>
          <li id="noti_Container">
          <div id="noti_Counter"></div>
          <div id="noti_Button"></div>    
          <div id="notifications">
          <h3 class="h3-class">Notifications</h3>
          </div>
          </li>
        <% end %>
        <li><a>Signed in as <%= current_user.email %></a></li>
        <% if current_user.is_admin? == false %>
          <li><%= link_to 'View Orders', invoices_path %></li>
          <li><%= link_to "View Cart  (#{current_user.cart.cart_items.count})", cart_items_path %></li>
        <% end %>
        <% if current_user.picture && current_user.picture.image_url %> 
          <li>
            <%= image_tag(current_user.picture.image_url(:thumbnail, version: current_user.picture.image.file.version), width: 50, height: 50, class:"profile-image img-circle") %>
          </li>
        <% elsif current_user.profile_pic %>
          <li><%= image_tag current_user.profile_pic , width: 50, height: 50, class:"profile-image img-circle" %></li>
        <% end %>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">My Account
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><a href="/users/sign_up"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span> Sign In</a></li>
        <li> <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %></li>
        <li><%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopping</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>
    <%= render 'layouts/topnav' %>
    <div class="notice">
      <% if flash[:notice] %>
        <p style="color: green;" ><%= flash[:notice] %></p>
      <% end %>
    </div>  
    <% if current_user && (current_user.is_admin? || current_user.is_seller?) %>
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-2">
            <%= render 'layouts/sidenav' %>
        </div>
          <div class="col-md-10"><%= yield %></div>
      </div>
    <% else %>
      <div class="container-fluid">
      <div class="row">
        <%= yield %>
      </div>
      </div>
    <% end %>
  </body>
</html>